version: "1"

services:
  - type: web
    name: timetable-api
    env: docker
    region: singapore
    plan: free
    # It overrides the Dockerfile locally just for Render
    dockerCommand: ./render-start.sh
    envVars:
      - key: DATABASE_URL
        sync: false #Neon/Supabase URL
      - key: REDIS_URL
        sync: false
    envGroups:
      - timetable-shared-env

envVarGroups:
  - name: timetable-shared-env
    envVars:
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "15"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: SECRET_KEY
        sync: false