"""empty message

Revision ID: 5018f78d3fd3
Revises: cca30db599c5
Create Date: 2026-02-23 14:47:05.422977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5018f78d3fd3'
down_revision: Union[str, Sequence[str], None] = 'cca30db599c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lab_assignments_class_id_fkey'), 'lab_assignments', type_='foreignkey')
    op.drop_constraint(op.f('lab_assignments_subject_id_fkey'), 'lab_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'lab_assignments', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lab_assignments', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lab_assignments', type_='foreignkey')
    op.drop_constraint(None, 'lab_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('lab_assignments_subject_id_fkey'), 'lab_assignments', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(op.f('lab_assignments_class_id_fkey'), 'lab_assignments', 'classes', ['class_id'], ['id'])
    # ### end Alembic commands ###
