"""empty message

Revision ID: dff3d3148ba7
Revises: b120c9aac327
Create Date: 2026-02-21 11:50:54.804404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff3d3148ba7'
down_revision: Union[str, Sequence[str], None] = 'b120c9aac327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slots', sa.Integer(), nullable=False),
    sa.Column('days', sa.ARRAY(sa.Enum('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='weekday')), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('completed', 'pending', 'failed', name='timetablestatus'), nullable=False),
    sa.Column('violations', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('room_name', sa.String(), nullable=False),
    sa.Column('isLab', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('min_classes_day', sa.Integer(), nullable=True),
    sa.Column('max_classes_day', sa.Integer(), nullable=True),
    sa.Column('min_classes_week', sa.Integer(), nullable=True),
    sa.Column('max_classes_week', sa.Integer(), nullable=True),
    sa.Column('min_classes_consecutive', sa.Integer(), nullable=True),
    sa.Column('max_classes_consecutive', sa.Integer(), nullable=True),
    sa.Column('isLab', sa.Boolean(), nullable=False),
    sa.Column('hardness', sa.Enum('low', 'med', 'high', name='hardness'), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_classes_week', sa.Integer(), nullable=True),
    sa.Column('max_classes_day', sa.Integer(), nullable=True),
    sa.Column('max_classes_consecutive', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_assignments',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('class_id', 'subject_id')
    )
    op.create_table('teacher_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('class_teacher', 'subject_teacher', name='teacherrole'), nullable=False),
    sa.Column('morning_class_days', sa.ARRAY(sa.Enum('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='weekdayenum')), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Enum('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='weekdayenum'), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable_entries')
    op.drop_table('teacher_assignments')
    op.drop_table('lab_assignments')
    op.drop_table('teachers')
    op.drop_table('subjects')
    op.drop_table('classes')
    op.drop_table('timetables')
    # ### end Alembic commands ###
